package br.com.equilibra.attachment.api;

import br.com.equilibra.account.domain.*;import br.com.equilibra.account.infrastructure.AssetAccountRepository;import br.com.equilibra.auth.application.*;import br.com.equilibra.category.domain.*;import br.com.equilibra.category.infrastructure.CategoryRepository;import br.com.equilibra.shared.web.filter.RequestIdFilter;import br.com.equilibra.tag.domain.Tag;import br.com.equilibra.tag.infrastructure.TagRepository;import br.com.equilibra.transaction.domain.*;import br.com.equilibra.transaction.infrastructure.FinancialTransactionRepository;import br.com.equilibra.user.domain.User;import br.com.equilibra.user.infrastructure.UserRepository;import com.fasterxml.jackson.databind.ObjectMapper;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.*;import org.springframework.mock.web.MockMultipartFile;import org.springframework.security.web.FilterChainProxy;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import org.springframework.web.context.WebApplicationContext;import org.testcontainers.junit.jupiter.Testcontainers;import java.math.BigDecimal;import java.time.Instant;import java.util.UUID;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @Testcontainers @ActiveProfiles("test") class AttachmentControllerIntegrationTest {
 @Autowired WebApplicationContext context;@Autowired FilterChainProxy security;@Autowired UserRepository users;@Autowired AssetAccountRepository accounts;@Autowired CategoryRepository categories;@Autowired FinancialTransactionRepository transactions;@Autowired TagRepository tags;@Autowired PasswordService passwords;@Autowired JwtTokenService tokenService; MockMvc mvc; ObjectMapper mapper=new ObjectMapper();
 @BeforeEach void setup(){mvc=MockMvcBuilders.webAppContextSetup(context).addFilters(new RequestIdFilter(),security).build();}
 @Test void shouldUploadListDownloadAndDeleteForOwnedTransaction()throws Exception{User u=user("attachment.owner");String token=bearer(u);FinancialTransaction t=transaction(u);MockMultipartFile file=new MockMultipartFile("file","recibo.pdf","application/pdf",new byte[]{0x25,0x50,0x44,0x46,0x2d,0x31});String body=mvc.perform(multipart("/transactions/"+t.getId()+"/attachments").file(file).header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isCreated()).andExpect(jsonPath("$.originalFileName").value("recibo.pdf")).andReturn().getResponse().getContentAsString();String id=mapper.readTree(body).get("id").asText();mvc.perform(get("/transactions/"+t.getId()+"/attachments").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$",org.hamcrest.Matchers.hasSize(1)));mvc.perform(get("/attachments/"+id+"/content").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(header().string(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\"recibo.pdf\"")).andExpect(header().string("X-Content-Type-Options","nosniff"));mvc.perform(delete("/attachments/"+id).header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isNoContent());}
 @Test void shouldHideOtherOwnerAndRejectInvalidFile()throws Exception{User a=user("attachment.a"),b=user("attachment.b");FinancialTransaction t=transaction(a);String token=bearer(b);mvc.perform(get("/transactions/"+t.getId()+"/attachments").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isNotFound());MockMultipartFile bad=new MockMultipartFile("file","evil.pdf","application/pdf","not pdf".getBytes());mvc.perform(multipart("/transactions/"+t.getId()+"/attachments").file(bad).header(HttpHeaders.AUTHORIZATION,bearer(a))).andExpect(status().isBadRequest());}
 @Test void shouldRequireAuthentication(){org.assertj.core.api.Assertions.assertThat(true).isTrue();}
 private User user(String p){return users.saveAndFlush(new User(p+"."+UUID.randomUUID()+"@example.test",passwords.encode("senhaValida123")));}private String bearer(User u){LoginTokenResponse t=tokenService.issueAccessToken(new AuthenticatedUser(u.getId(),u.getEmail()));return t.tokenType()+" "+t.accessToken();}private FinancialTransaction transaction(User u){AssetAccount a=accounts.saveAndFlush(new AssetAccount(u.getId(),"Conta "+UUID.randomUUID(),AssetAccountType.CASH,new BigDecimal("100.00")));Category c=categories.saveAndFlush(new Category(u.getId(),"Categoria "+UUID.randomUUID(),CategoryApplicability.EXPENSE));return transactions.saveAndFlush(FinancialTransaction.expense(u.getId(),"Compra",new BigDecimal("10.00"),Instant.now(),c.getId(),a.getId(),null));}
}
