import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormControl, FormGroup, NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { AssetAccountsApiService } from '../../asset-accounts/data-access/asset-accounts-api.service';
import { AssetAccount } from '../../asset-accounts/models/asset-account.models';
import { ContentPanelComponent } from '../../../shared/ui/content-panel/content-panel.component';
import { EmptyStateComponent } from '../../../shared/ui/empty-state/empty-state.component';
import { PageHeaderComponent } from '../../../shared/ui/page-header/page-header.component';
import { CategoryReportApiService } from '../data-access/category-report-api.service';
import { CategoryReportFilters, CategoryReportResponse } from '../models/category-report.models';

interface CategoryReportForm { from: FormControl<string>; to: FormControl<string>; accountIds: FormControl<string[]>; }

@Component({
  selector: 'app-category-report-page', standalone: true,
  imports: [CommonModule, ReactiveFormsModule, MatButtonModule, MatFormFieldModule, MatIconModule, MatSelectModule, ContentPanelComponent, EmptyStateComponent, PageHeaderComponent],
  template: `<main class="category-report-page"><app-page-header title="Relatório por categoria" subtitle="Entenda como suas receitas e despesas estão distribuídas entre as categorias."/><app-content-panel title="Filtros do relatório" subtitle="Escolha o período e as contas que deseja analisar."><form class="report-filters" [formGroup]="form" (ngSubmit)="apply()"><mat-form-field appearance="outline"><mat-label>Data inicial</mat-label><input matInput type="date" formControlName="from"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Data final</mat-label><input matInput type="date" formControlName="to"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Contas</mat-label><mat-select multiple formControlName="accountIds"><mat-option [value]="ALL">Todas as contas</mat-option>@for(account of accounts();track account.id){<mat-option [value]="account.id">{{account.name}}{{account.active?'':' (Inativa)'}}</mat-option>}</mat-select></mat-form-field><div class="actions"><button mat-flat-button color="primary" type="submit" [disabled]="loading()">Aplicar filtros</button><button mat-button type="button" (click)="reset()" [disabled]="loading()">Restaurar</button></div></form>@if(error()){<p class="form-error" role="alert">{{error()}}</p>}</app-content-panel>@if(loading()){<div class="state" role="status">Carregando relatório...</div>}@else if(apiError()){<div class="state error" role="alert">{{apiError()}} <button mat-stroked-button type="button" (click)="retry()">Tentar novamente</button></div>}@if(report();as value){<section class="metrics" aria-label="Resumo por categoria"><article><span>Receitas</span><strong>{{money(value.incomeTotal)}}</strong></article><article><span>Despesas</span><strong>{{money(value.expenseTotal)}}</strong></article><article><span>Resultado financeiro</span><strong>{{money(value.netResult)}}</strong></article></section><app-content-panel title="Categorias" subtitle="Receitas e despesas permanecem separadas por categoria."><div class="table-wrap"><table><thead><tr><th>Categoria</th><th>Aplicabilidade</th><th>Receitas</th><th>Despesas</th><th>Resultado</th></tr></thead><tbody>@for(item of value.categories;track item.categoryId){<tr><td>{{item.categoryName}}</td><td>{{item.applicability}}</td><td>{{money(item.incomeTotal)}}</td><td>{{money(item.expenseTotal)}}</td><td>{{money(item.netResult)}}</td></tr>}</tbody></table></div>@if(value.categories.length===0){<app-empty-state icon="category" iconVariant="inbox" title="Nenhuma categoria no período" description="Não há receitas ou despesas para os filtros selecionados." [centered]="false"/>}</app-content-panel>}</main>`,
  styles: `.category-report-page{display:flex;flex-direction:column;gap:var(--space-6);padding-bottom:var(--space-8)}.report-filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--space-4)}.actions{display:flex;align-items:center;gap:var(--space-2)}.form-error,.error{color:var(--color-danger-700)}.state{padding:var(--space-8);text-align:center;color:var(--text-secondary)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:var(--space-4)}.metrics article{display:flex;flex-direction:column;gap:var(--space-2);padding:var(--space-5);border:1px solid var(--card-border);border-radius:var(--radius-lg);background:var(--card-bg)}.metrics span{color:var(--text-secondary)}.metrics strong{font-size:var(--font-size-h3);color:var(--text-primary)}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:var(--space-3);border-bottom:1px solid var(--card-border);text-align:left;white-space:nowrap}@media(max-width:767px){.report-filters,.metrics{grid-template-columns:1fr}.table-wrap{overflow-x:hidden}table,thead,tbody,tr,th,td{display:block}thead{display:none}tr{padding:var(--space-3);border-bottom:1px solid var(--card-border)}td{display:flex;justify-content:space-between;white-space:normal}.metrics article{padding:var(--space-4)}}`,
})
export class CategoryReportPageComponent implements OnInit {
 readonly ALL='ALL'; readonly accounts=signal<AssetAccount[]>([]); readonly report=signal<CategoryReportResponse|null>(null); readonly loading=signal(false); readonly error=signal<string|null>(null); readonly apiError=signal<string|null>(null); readonly form:FormGroup<CategoryReportForm>; private filters:CategoryReportFilters; private readonly api=inject(CategoryReportApiService); private readonly accountsApi=inject(AssetAccountsApiService);
 constructor(private readonly fb:NonNullableFormBuilder){const d=this.defaults();this.form=this.fb.group({from:this.fb.control(d.from,Validators.required),to:this.fb.control(d.to,Validators.required),accountIds:this.fb.control<string[]>([])});this.filters={from:this.start(d.from),to:this.end(d.to),accountIds:[]};}
 ngOnInit(){this.accountsApi.list(true).subscribe({next:v=>this.accounts.set(v),error:()=>undefined});this.load();}
 apply(){const v=this.form.getRawValue();if(!v.from||!v.to||v.from>=v.to){this.error.set('A data inicial deve ser anterior à data final.');return;}this.error.set(null);this.filters={from:this.start(v.from),to:this.end(v.to),accountIds:v.accountIds.includes(this.ALL)?[]:[...new Set(v.accountIds)]};this.load();}
 reset(){const d=this.defaults();this.form.reset({from:d.from,to:d.to,accountIds:[]});this.error.set(null);this.filters={from:this.start(d.from),to:this.end(d.to),accountIds:[]};this.load();}
 retry(){this.load();} money(v:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);}
 private load(){this.loading.set(true);this.apiError.set(null);this.api.query(this.filters).subscribe({next:v=>{this.report.set(v);this.loading.set(false)},error:()=>{this.loading.set(false);this.apiError.set('Não foi possível carregar o relatório por categoria.')}});}
 private defaults(){const n=new Date();return{from:`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,to:`${n.getFullYear()}-${String(n.getMonth()+2).padStart(2,'0')}-01`};}private start(v:string){const [y,m,d]=v.split('-').map(Number);return new Date(Date.UTC(y,m-1,d)).toISOString();}private end(v:string){const [y,m,d]=v.split('-').map(Number);return new Date(Date.UTC(y,m-1,d+1)).toISOString();}
}
