package br.com.equilibra.budget.application;
import br.com.equilibra.budget.api.BudgetDtos; import br.com.equilibra.budget.domain.CategoryBudget; import br.com.equilibra.budget.infrastructure.CategoryBudgetRepository; import br.com.equilibra.category.domain.Category; import br.com.equilibra.category.domain.CategoryApplicability; import br.com.equilibra.category.infrastructure.CategoryRepository; import br.com.equilibra.shared.api.CurrentUser; import br.com.equilibra.shared.web.exception.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.YearMonth; import java.util.*;
@Service public class CategoryBudgetService { private final CategoryBudgetRepository budgets; private final CategoryRepository categories; private final CurrentUser currentUser; public CategoryBudgetService(CategoryBudgetRepository b,CategoryRepository c,CurrentUser u){budgets=b;categories=c;currentUser=u;}
 @Transactional public BudgetDtos.Response create(BudgetDtos.Create request){String owner=owner();Category category=category(request.categoryId(),owner);if(!category.isActive()||category.getApplicability()==CategoryApplicability.INCOME)throw new IllegalArgumentException("category is not eligible");YearMonth ym=parse(request.month());if(budgets.findByOwnerIdAndCategoryIdAndYearAndMonth(owner,category.getId(),(short)ym.getYear(),(byte)ym.getMonthValue()).isPresent())throw new ResourceConflictException("Budget already exists.");try{return response(budgets.save(new CategoryBudget(owner,category.getId(),ym.getYear(),ym.getMonthValue(),request.plannedAmount())),category);}catch(DataIntegrityViolationException e){throw new ResourceConflictException("Budget already exists.");}}
 @Transactional(readOnly=true) public List<BudgetDtos.Response> list(){String owner=owner();return budgets.findAllByOwnerIdOrderByYearDescMonthDesc(owner).stream().map(b->response(b,category(b.getCategoryId(),owner))).toList();}
 @Transactional(readOnly=true) public BudgetDtos.Response get(String id){String owner=owner();CategoryBudget b=budgets.findByIdAndOwnerId(id,owner).orElseThrow(()->new ResourceNotFoundException("Budget not found."));return response(b,category(b.getCategoryId(),owner));}
 @Transactional public BudgetDtos.Response update(String id,BudgetDtos.Update request){String owner=owner();CategoryBudget b=budgets.findByIdAndOwnerId(id,owner).orElseThrow(()->new ResourceNotFoundException("Budget not found."));b.changeAmount(request.plannedAmount());return response(budgets.save(b),category(b.getCategoryId(),owner));}
 @Transactional public void delete(String id){String owner=owner();if(budgets.findByIdAndOwnerId(id,owner).isEmpty())throw new ResourceNotFoundException("Budget not found.");budgets.deleteById(id);}
 private Category category(String id,String owner){return categories.findByIdAndOwnerId(id,owner).orElseThrow(()->new ResourceNotFoundException("Category not found."));} private String owner(){return currentUser.id().toString();} private YearMonth parse(String value){try{return YearMonth.parse(value);}catch(Exception e){throw new IllegalArgumentException("month must use YYYY-MM");}} private BudgetDtos.Response response(CategoryBudget b,Category c){return new BudgetDtos.Response(b.getId(),c.getId(),c.getName(),c.isActive(),b.getYear(),b.getMonth(),b.getPlannedAmount(),b.getCreatedAt(),b.getUpdatedAt());}}
