package br.com.equilibra.transaction.application;
import br.com.equilibra.account.domain.AssetAccount; import br.com.equilibra.account.infrastructure.AssetAccountRepository; import br.com.equilibra.category.domain.*; import br.com.equilibra.category.infrastructure.CategoryRepository; import br.com.equilibra.shared.api.CurrentUser; import br.com.equilibra.shared.web.exception.*; import br.com.equilibra.transaction.api.*; import br.com.equilibra.transaction.domain.*; import br.com.equilibra.transaction.infrastructure.FinancialTransactionRepository; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.UUID;
@Service public class IncomeService {
 private static final int MAX=100; private final FinancialTransactionRepository tx; private final AssetAccountRepository accounts; private final CategoryRepository categories; private final CurrentUser current;
 public IncomeService(FinancialTransactionRepository tx,AssetAccountRepository accounts,CategoryRepository categories,CurrentUser current){this.tx=tx;this.accounts=accounts;this.categories=categories;this.current=current;}
 @Transactional public IncomeResponse create(CreateIncomeRequest r){String o=owner(); AssetAccount a=account(r.accountId(),o); Category c=category(r.categoryId(),o); return IncomeResponse.from(tx.save(FinancialTransaction.income(o,r.description(),r.amount(),r.occurredAt(),c.getId(),a.getId(),r.notes())));}
 @Transactional(readOnly=true) public IncomePageResponse list(int page,int size,boolean cancelled){if(page<0||size<1||size>MAX)throw new IllegalArgumentException("Invalid pagination parameters."); Page<FinancialTransaction> p=tx.findPageByOwnerAndTypeAndStatus(owner(),TransactionType.INCOME,cancelled?null:TransactionStatus.ACTIVE,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"occurredAt").and(Sort.by(Sort.Direction.DESC,"id"))));return new IncomePageResponse(p.getContent().stream().map(IncomeResponse::from).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 @Transactional(readOnly=true) public IncomeResponse get(String id){return IncomeResponse.from(find(id));}
 @Transactional public IncomeResponse update(String id,UpdateIncomeRequest r){FinancialTransaction t=find(id);if(t.getStatus()==TransactionStatus.CANCELLED)throw new ResourceConflictException("Cancelled incomes cannot be edited."); AssetAccount a=account(r.accountId(),owner());Category c=category(r.categoryId(),owner());t.changeDescription(r.description());t.changeAmount(r.amount());t.changeOccurredAt(r.occurredAt());t.changeNotes(r.notes());t.changeDestinationAccount(a.getId());t.changeCategory(c.getId());return IncomeResponse.from(tx.save(t));}
 @Transactional public IncomeResponse cancel(String id){FinancialTransaction t=find(id);try{t.cancel();return IncomeResponse.from(tx.save(t));}catch(IllegalStateException e){throw new ResourceConflictException("Income is already cancelled.");}}
 private FinancialTransaction find(String id){uuid(id,"id");return tx.findByIdAndOwnerIdAndType(id,owner(),TransactionType.INCOME).orElseThrow(()->new ResourceNotFoundException("Income not found."));}
 private AssetAccount account(String id,String o){uuid(id,"accountId");AssetAccount a=accounts.findByIdAndOwnerId(id,o).orElseThrow(()->new ResourceNotFoundException("Asset account not found."));if(!a.isActive())throw new ResourceConflictException("Asset account is inactive.");return a;}
 private Category category(String id,String o){uuid(id,"categoryId");Category c=categories.findByIdAndOwnerId(id,o).orElseThrow(()->new ResourceNotFoundException("Category not found."));if(!c.isActive())throw new ResourceConflictException("Category is inactive.");if(c.getApplicability()!=CategoryApplicability.INCOME&&c.getApplicability()!=CategoryApplicability.BOTH)throw new ResourceConflictException("Category is not applicable to incomes.");return c;}
 private String owner(){return current.id().toString();} private static void uuid(String v,String f){try{UUID.fromString(v);}catch(Exception e){throw new IllegalArgumentException(f+" must be a valid UUID.",e);}}
}
