package br.com.equilibra.goal.application;
import br.com.equilibra.goal.api.GoalDtos; import br.com.equilibra.goal.domain.*; import br.com.equilibra.goal.infrastructure.*; import br.com.equilibra.shared.api.CurrentUser; import br.com.equilibra.shared.web.exception.ResourceNotFoundException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class FinancialGoalService {private final FinancialGoalRepository goals;private final GoalContributionRepository contributions;private final CurrentUser currentUser;public FinancialGoalService(FinancialGoalRepository g,GoalContributionRepository c,CurrentUser u){goals=g;contributions=c;currentUser=u;} private String owner(){return currentUser.id().toString();}
@Transactional public GoalDtos.Response create(GoalDtos.Create r){FinancialGoal g=new FinancialGoal(owner(),r.name(),r.description(),r.targetAmount(),r.targetDate());return response(goals.save(g));}
@Transactional(readOnly=true) public List<GoalDtos.Response> list(){return goals.findAllByOwnerIdOrderByCreatedAtDesc(owner()).stream().map(this::response).toList();}
@Transactional(readOnly=true) public GoalDtos.Response get(String id){return response(find(id));}
@Transactional public GoalDtos.Response update(String id,GoalDtos.Update r){FinancialGoal g=find(id);if(g.getStatus()!=FinancialGoalStatus.ACTIVE)throw new IllegalStateException("only active goals can be edited");g.rename(r.name());g.changeTarget(r.targetAmount());return response(goals.save(g));}
@Transactional public GoalDtos.Response contribute(String id,GoalDtos.Contribution r){FinancialGoal g=find(id);if(g.getStatus()!=FinancialGoalStatus.ACTIVE)throw new IllegalStateException("goal is not active");contributions.save(new GoalContribution(owner(),id,r.amount(),r.occurredAt()==null?Instant.now():r.occurredAt(),r.note()));return response(g);}
@Transactional public GoalDtos.Response complete(String id){FinancialGoal g=find(id);g.complete();return response(goals.save(g));}
@Transactional public GoalDtos.Response archive(String id){FinancialGoal g=find(id);g.archive();return response(goals.save(g));}
private FinancialGoal find(String id){return goals.findByIdAndOwnerId(id,owner()).orElseThrow(()->new ResourceNotFoundException("Goal not found."));} private GoalDtos.Response response(FinancialGoal g){BigDecimal progress=contributions.sumForGoal(owner(),g.getId()).setScale(2),remaining=g.getTargetAmount().subtract(progress);BigDecimal pct=g.getTargetAmount().signum()==0?null:progress.multiply(BigDecimal.valueOf(100)).divide(g.getTargetAmount(),2,RoundingMode.HALF_UP);return new GoalDtos.Response(g.getId(),g.getName(),g.getDescription(),g.getTargetAmount(),g.getTargetDate(),g.getStatus(),progress,remaining,pct,g.getCreatedAt(),g.getUpdatedAt());}}
