package br.com.equilibra.commitment.application;
import br.com.equilibra.account.infrastructure.AssetAccountRepository; import br.com.equilibra.category.infrastructure.CategoryRepository; import br.com.equilibra.category.domain.*; import br.com.equilibra.commitment.api.*; import br.com.equilibra.commitment.domain.*; import br.com.equilibra.commitment.infrastructure.*; import br.com.equilibra.recurrence.domain.*; import br.com.equilibra.recurrence.infrastructure.RecurrenceRuleRepository; import br.com.equilibra.shared.api.CurrentUser; import br.com.equilibra.shared.web.exception.*; import br.com.equilibra.transaction.api.*; import br.com.equilibra.transaction.application.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class FinancialCommitmentService{
 private final FinancialCommitmentRepository repo; private final CurrentUser current; private final AssetAccountRepository accounts; private final CategoryRepository categories; private final RecurrenceRuleRepository rules; private final ExpenseService expenses; private final IncomeService incomes;
 public FinancialCommitmentService(FinancialCommitmentRepository r,CurrentUser c,AssetAccountRepository a,CategoryRepository cat,RecurrenceRuleRepository rules,ExpenseService e,IncomeService i){repo=r;current=c;accounts=a;categories=cat;this.rules=rules;expenses=e;incomes=i;}
 @Transactional public CommitmentDtos.Response create(CommitmentDtos.Create r){if(r.recurrenceRuleId()!=null){var rule=rules.findByIdAndOwnerId(r.recurrenceRuleId(),owner()).orElseThrow(()->new ResourceNotFoundException("Recurrence rule not found."));if((rule.getType()==RecurrenceType.EXPENSE&&r.type()!=CommitmentType.EXPENSE)||(rule.getType()==RecurrenceType.INCOME&&r.type()!=CommitmentType.INCOME))throw new ResourceConflictException("Commitment type is incompatible with recurrence rule.");}validateRefs(r.type(),r.accountId(),r.categoryId());return response(repo.save(new FinancialCommitment(owner(),r.type(),r.description(),r.plannedAmount(),r.dueDate(),r.accountId(),r.categoryId(),r.recurrenceRuleId())),LocalDate.now());}
 @Transactional(readOnly=true) public Page<CommitmentDtos.Response> list(CommitmentDtos.Filter filter,Pageable pageable){return repo.search(owner(),filter.type(),filter.status(),filter.from(),filter.to(),filter.accountId(),filter.categoryId(),filter.recurrenceRuleId(),pageable).map(x->response(x,LocalDate.now()));}
 @Transactional(readOnly=true) public CommitmentDtos.Response get(String id){return response(find(id),LocalDate.now());}
 @Transactional public CommitmentDtos.Response update(String id,CommitmentDtos.Update r){FinancialCommitment x=find(id);x.rename(r.description());x.changeAmount(r.plannedAmount());x.changeDueDate(r.dueDate());validateRefs(x.getType(),r.accountId(),r.categoryId());x.changeReferences(r.accountId(),r.categoryId());return response(repo.save(x),LocalDate.now());}
 @Transactional public CommitmentDtos.Response cancel(String id){FinancialCommitment x=find(id);x.cancel();return response(repo.save(x),LocalDate.now());}
 @Transactional public List<CommitmentDtos.Response> generate(CommitmentDtos.Generate request){if(request.from()==null||request.to()==null||request.to().isBefore(request.from())||request.to().isAfter(request.from().plusMonths(12)))throw new IllegalArgumentException("Generation interval must be between 0 and 12 months.");List<CommitmentDtos.Response> result=new ArrayList<>();for(var rule:rules.findAllByOwnerIdOrderByCreatedAtDesc(owner())){if(rule.getStatus()!=RecurrenceStatus.ACTIVE)continue;LocalDate date=rule.getStartDate().isAfter(request.from())?rule.getStartDate():request.from();while(!date.isAfter(request.to())){if(!date.isBefore(rule.getStartDate())&&(rule.getEndDate()==null||!date.isAfter(rule.getEndDate()))){LocalDate due=date.withDayOfMonth(Math.min(rule.getDueDay(),date.lengthOfMonth()));if((rule.getFrequency()==RecurrenceFrequency.MONTHLY&&due.getDayOfMonth()==rule.getDueDay()||rule.getFrequency()==RecurrenceFrequency.YEARLY&&due.getMonth()==rule.getStartDate().getMonth()&&due.getDayOfMonth()==Math.min(rule.getDueDay(),due.lengthOfMonth()))){var existing=repo.findByOwnerIdAndRecurrenceRuleIdAndDueDate(owner(),rule.getId(),due);if(existing.isEmpty()){validateRefs(rule.getType()==RecurrenceType.EXPENSE?CommitmentType.EXPENSE:CommitmentType.INCOME,rule.getAccountId(),rule.getCategoryId());result.add(response(repo.save(new FinancialCommitment(owner(),rule.getType()==RecurrenceType.EXPENSE?CommitmentType.EXPENSE:CommitmentType.INCOME,rule.getDescription(),rule.getAmount(),due,rule.getAccountId(),rule.getCategoryId(),rule.getId())),LocalDate.now()));}}}date=date.plusMonths(rule.getFrequency()==RecurrenceFrequency.MONTHLY?1:12);}}return result;}
 @Transactional public CommitmentDtos.Response settle(String id,CommitmentDtos.Settle r){FinancialCommitment x=find(id);if(x.getStatus()!=CommitmentStatus.PENDING)throw new ResourceConflictException("Commitment is not pending.");String tx;if(x.getType()==CommitmentType.EXPENSE)tx=expenses.create(new CreateExpenseRequest(x.getDescription(),r.occurredAt(),x.getAccountId(),r.amount(),x.getCategoryId(),null,null)).id();else tx=incomes.create(new CreateIncomeRequest(x.getDescription(),r.occurredAt(),x.getAccountId(),r.amount(),x.getCategoryId(),null,null)).id();x.settle(tx,r.occurredAt());return response(repo.save(x),LocalDate.now());}
 private FinancialCommitment find(String id){return repo.findByIdAndOwnerId(id,owner()).orElseThrow(()->new ResourceNotFoundException("Commitment not found."));}
 private void validateRefs(CommitmentType type,String account,String category){if(accounts.findByIdAndOwnerId(account,owner()).filter(a->a.isActive()).isEmpty())throw new ResourceConflictException("Asset account is inactive or unavailable.");var c=categories.findByIdAndOwnerId(category,owner()).filter(x->x.isActive()).orElseThrow(()->new ResourceConflictException("Category is inactive or unavailable."));if(type==CommitmentType.EXPENSE&&c.getApplicability()==CategoryApplicability.INCOME||type==CommitmentType.INCOME&&c.getApplicability()==CategoryApplicability.EXPENSE)throw new ResourceConflictException("Category is incompatible.");}
 private String owner(){return current.id().toString();} private CommitmentDtos.Response response(FinancialCommitment x,LocalDate today){return new CommitmentDtos.Response(x.getId(),x.getType(),x.getDescription(),x.getPlannedAmount(),x.getDueDate(),x.getAccountId(),x.getCategoryId(),x.getRecurrenceRuleId(),x.getStatus(),x.getFinancialTransactionId(),x.getSettledAt(),x.getStatus()==CommitmentStatus.PENDING&&x.getDueDate().isBefore(today),x.getCreatedAt(),x.getUpdatedAt());}
}
