package br.com.equilibra.commitment.api;

import br.com.equilibra.account.domain.*; import br.com.equilibra.account.infrastructure.AssetAccountRepository; import br.com.equilibra.category.domain.*; import br.com.equilibra.category.infrastructure.CategoryRepository; import br.com.equilibra.auth.application.*; import br.com.equilibra.user.domain.User; import br.com.equilibra.user.infrastructure.UserRepository; import com.fasterxml.jackson.databind.ObjectMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.web.FilterChainProxy; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.*; import org.springframework.test.web.servlet.setup.MockMvcBuilders; import org.springframework.web.context.WebApplicationContext;
import java.math.BigDecimal; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @ActiveProfiles("test") class FinancialCommitmentControllerIntegrationTest {
 @Autowired WebApplicationContext context; @Autowired FilterChainProxy security; @Autowired UserRepository users; @Autowired AssetAccountRepository accounts; @Autowired CategoryRepository categories; @Autowired PasswordService passwords; @Autowired JwtTokenService tokens; ObjectMapper mapper=new ObjectMapper(); MockMvc mvc;
 @BeforeEach void setup(){mvc=MockMvcBuilders.webAppContextSetup(context).addFilters(security).build();}
 @Test void shouldCreateListFilterAndCancelWithoutOwnerId() throws Exception {User u=user();var a=accounts.saveAndFlush(new AssetAccount(u.getId(),"Cash",AssetAccountType.CASH,new BigDecimal("1000")));var c=categories.saveAndFlush(new Category(u.getId(),"Expenses"+UUID.randomUUID(),CategoryApplicability.EXPENSE));String token=bearer(u);String body="{\"type\":\"EXPENSE\",\"description\":\"Internet\",\"plannedAmount\":129.90,\"dueDate\":\"2026-10-10\",\"accountId\":\""+a.getId()+"\",\"categoryId\":\""+c.getId()+"\"}";var result=mvc.perform(post("/commitments").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("PENDING")).andExpect(jsonPath("$.overdue").exists()).andReturn();String id=mapper.readTree(result.getResponse().getContentAsString()).get("id").asText();mvc.perform(get("/commitments?status=PENDING&size=10").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1));mvc.perform(post("/commitments/"+id+"/cancel").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CANCELLED"));}
 @Test void settleExpenseAndRetryIsConflict() throws Exception {User u=user();var a=accounts.saveAndFlush(new AssetAccount(u.getId(),"Cash",AssetAccountType.CASH,new BigDecimal("1000")));var c=categories.saveAndFlush(new Category(u.getId(),"Expense"+UUID.randomUUID(),CategoryApplicability.EXPENSE));String token=bearer(u);String body="{\"type\":\"EXPENSE\",\"description\":\"Expense\",\"plannedAmount\":200,\"dueDate\":\"2026-10-10\",\"accountId\":\""+a.getId()+"\",\"categoryId\":\""+c.getId()+"\"}";var created=mvc.perform(post("/commitments").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(body)).andReturn();String id=mapper.readTree(created.getResponse().getContentAsString()).get("id").asText();var settle="{\"occurredAt\":\"2026-10-10T12:00:00Z\",\"amount\":200}";mvc.perform(post("/commitments/"+id+"/settle").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(settle)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SETTLED"));mvc.perform(post("/commitments/"+id+"/settle").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(settle)).andExpect(status().isConflict());}
 @Test void generationIsIdempotentForMonthlyDayThirtyOne() throws Exception {User u=user();var a=accounts.saveAndFlush(new AssetAccount(u.getId(),"Cash",AssetAccountType.CASH,new BigDecimal("1000")));var c=categories.saveAndFlush(new Category(u.getId(),"Expense"+UUID.randomUUID(),CategoryApplicability.EXPENSE));String token=bearer(u);String rule="{\"type\":\"EXPENSE\",\"description\":\"Monthly\",\"amount\":129.90,\"categoryId\":\""+c.getId()+"\",\"accountId\":\""+a.getId()+"\",\"frequency\":\"MONTHLY\",\"startDate\":\"2026-01-01\",\"dueDay\":31}";mvc.perform(post("/recurrences").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(rule)).andExpect(status().isCreated());String generate="{\"from\":\"2026-01-01\",\"to\":\"2026-04-30\"}";mvc.perform(post("/commitments/generate").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(generate)).andExpect(status().isOk()).andExpect(jsonPath("$[1].dueDate").value("2026-02-28"));mvc.perform(post("/commitments/generate").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(generate)).andExpect(status().isOk()).andExpect(jsonPath("$").isEmpty());}
 @Test void foreignCommitmentIsNotVisible() throws Exception {User a=user();User b=user();var account=accounts.saveAndFlush(new AssetAccount(a.getId(),"Cash",AssetAccountType.CASH,new BigDecimal("10")));var cat=categories.saveAndFlush(new Category(a.getId(),"Expense"+UUID.randomUUID(),CategoryApplicability.EXPENSE));String token=bearer(a);String body="{\"type\":\"EXPENSE\",\"description\":\"X\",\"plannedAmount\":1,\"dueDate\":\"2026-10-10\",\"accountId\":\""+account.getId()+"\",\"categoryId\":\""+cat.getId()+"\"}";var response=mvc.perform(post("/commitments").header(HttpHeaders.AUTHORIZATION,token).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(body)).andReturn();String id=mapper.readTree(response.getResponse().getContentAsString()).get("id").asText();mvc.perform(get("/commitments/"+id).header(HttpHeaders.AUTHORIZATION,bearer(b))).andExpect(status().isNotFound());}
 private User user(){return users.saveAndFlush(new User("commit-"+UUID.randomUUID()+"@example.test",passwords.encode("senhaValida123")));} private String bearer(User u){var t=tokens.issueAccessToken(new AuthenticatedUser(u.getId(),u.getEmail()));return t.tokenType()+" "+t.accessToken();}
}
